/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AcademicCategory = IDL.Variant({
  'curriculum' : IDL.Null,
  'exam_schedule' : IDL.Null,
  'timetable' : IDL.Null,
});
export const AcademicResource = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'storageKey' : IDL.Text,
  'category' : AcademicCategory,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addAcademicResource' : IDL.Func(
      [IDL.Text, AcademicCategory, IDL.Text, IDL.Text],
      [AcademicResource],
      [],
    ),
  'deleteAcademicResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAcademicResources' : IDL.Func(
      [IDL.Opt(AcademicCategory)],
      [IDL.Vec(AcademicResource)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AcademicCategory = IDL.Variant({
    'curriculum' : IDL.Null,
    'exam_schedule' : IDL.Null,
    'timetable' : IDL.Null,
  });
  const AcademicResource = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'storageKey' : IDL.Text,
    'category' : AcademicCategory,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'addAcademicResource' : IDL.Func(
        [IDL.Text, AcademicCategory, IDL.Text, IDL.Text],
        [AcademicResource],
        [],
      ),
    'deleteAcademicResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAcademicResources' : IDL.Func(
        [IDL.Opt(AcademicCategory)],
        [IDL.Vec(AcademicResource)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };