/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AcademicCategory = { 'curriculum' : null } |
  { 'exam_schedule' : null } |
  { 'timetable' : null };
export interface AcademicResource {
  'id' : string,
  'title' : string,
  'description' : string,
  'storageKey' : string,
  'category' : AcademicCategory,
  'uploadedAt' : bigint,
}
export interface _SERVICE {
  'addAcademicResource' : ActorMethod<
    [string, AcademicCategory, string, string],
    AcademicResource
  >,
  'deleteAcademicResource' : ActorMethod<[string], boolean>,
  'getAcademicResources' : ActorMethod<
    [[] | [AcademicCategory]],
    Array<AcademicResource>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];