/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AcademicResource {
    id: string;
    title: string;
    description: string;
    storageKey: string;
    category: AcademicCategory;
    uploadedAt: bigint;
}
export enum AcademicCategory {
    curriculum = "curriculum",
    exam_schedule = "exam_schedule",
    timetable = "timetable"
}
export interface backendInterface {
    addAcademicResource(title: string, category: AcademicCategory, description: string, storageKey: string): Promise<AcademicResource>;
    deleteAcademicResource(id: string): Promise<boolean>;
    getAcademicResources(category: AcademicCategory | null): Promise<Array<AcademicResource>>;
}
import type { AcademicCategory as _AcademicCategory, AcademicResource as _AcademicResource } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAcademicResource(arg0: string, arg1: AcademicCategory, arg2: string, arg3: string): Promise<AcademicResource> {
        if (this.processError) {
            try {
                const result = await this.actor.addAcademicResource(arg0, to_candid_AcademicCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_AcademicResource_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAcademicResource(arg0, to_candid_AcademicCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_AcademicResource_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAcademicResource(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAcademicResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAcademicResource(arg0);
            return result;
        }
    }
    async getAcademicResources(arg0: AcademicCategory | null): Promise<Array<AcademicResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicResources(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicResources(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AcademicCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicCategory): AcademicCategory {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AcademicResource_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicResource): AcademicResource {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    storageKey: string;
    category: _AcademicCategory;
    uploadedAt: bigint;
}): {
    id: string;
    title: string;
    description: string;
    storageKey: string;
    category: AcademicCategory;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        storageKey: value.storageKey,
        category: from_candid_AcademicCategory_n5(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    curriculum: null;
} | {
    exam_schedule: null;
} | {
    timetable: null;
}): AcademicCategory {
    return "curriculum" in value ? AcademicCategory.curriculum : "exam_schedule" in value ? AcademicCategory.exam_schedule : "timetable" in value ? AcademicCategory.timetable : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicResource>): Array<AcademicResource> {
    return value.map((x)=>from_candid_AcademicResource_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AcademicCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicCategory): _AcademicCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicCategory | null): [] | [_AcademicCategory] {
    return value === null ? candid_none() : candid_some(to_candid_AcademicCategory_n1(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicCategory): {
    curriculum: null;
} | {
    exam_schedule: null;
} | {
    timetable: null;
} {
    return value == AcademicCategory.curriculum ? {
        curriculum: null
    } : value == AcademicCategory.exam_schedule ? {
        exam_schedule: null
    } : value == AcademicCategory.timetable ? {
        timetable: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
